import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copy } from 'esbuild-plugin-copy';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Plugin to force pptxgenjs to use browser code paths in Obsidian (Electron).
// Electron has process.versions.node set, so pptxgenjs thinks it's Node.js
// and tries to import('node:https') / import('node:fs') which fail in Obsidian.
const pptxBrowserPlugin = {
	name: 'pptxgenjs-browser',
	setup(build) {
		build.onLoad({ filter: /pptxgenjs[/\\]dist[/\\]pptxgen\./ }, async (args) => {
			const fs = await import('fs');
			let contents = fs.readFileSync(args.path, 'utf8');
			// Replace isNode detection patterns (both readable and minified forms)
			contents = contents.replaceAll(
				/(?:const|var|let)\s+isNode\s*=\s*typeof process\s*!==?\s*['"]undefined['"]\s*&&\s*!!\(.*?\.node\).*?===?\s*['"]node['"]/g,
				'const isNode = false'
			);
			return { contents, loader: 'js' };
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	plugins: [pptxBrowserPlugin],
	external: [
		"obsidian",
		"electron",
		"chromium-bidi/lib/cjs/bidiMapper/bidiMapper.js",
		"emitter",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",		
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	//outfile: "vault/.obsidian/plugins/marp-slides/main.js", //for local dev!!!
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}